permalink: pretty
title: mrrobust - Two-sample Mendelian randomization in Stata
email: tom.palmer@bristol.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Stata package for two-sample Mendelian randomization analyses
baseurl: "/mrrobust" # the subpath of your site, e.g. /blog
url: "https://remlapmot.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: remlapmot
keywords: "Mendelian randomization, Stata, Two-sample"
author: Tom Palmer
repo: "https://github.com/remlapmot/mrrobust"
exclude: cscripts/README.md
# header_pages: 
  - index.md
  - docs/examples.md
#  - docs/mrrobust-examples.md
#  - docs/spiller-ije-2018-examples.md
#  - docs/markstat-call-R-example.md
#  - docs/rmarkdown-call-stata-example.md
#  - docs/save-estimates.md
#  - docs/mvcommands-example-2.md
  - docs/about.md

# Build settings
markdown: kramdown
# theme: jekyll-theme-primer 
theme: minima
google_analytics: UA-156933160-1
plugins:
  - jekyll-feed

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default
